# Generated by Django 5.1 on 2024-08-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
