# Generated by Django 5.1 on 2024-08-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
