# Generated by Django 5.1 on 2024-08-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_post_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_deleted",
        ),
    ]
